categories:

  - title: 'New features'
    labels:
      - 'enhancement'

  - title: 'Bug Fixes'
    labels:
      - 'bug'

  - title: 'Maintenance'
    labels:
      - 'code quality'
      - 'documentation'

  - title: 'Dependency updates'
    labels:
      -  'dependencies'

change-template: '- $TITLE #$NUMBER'

sort-direction: 'ascending'

template: |
  # What's Changed

  $CHANGES

  # Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS

replacers:
  - search: '/(?:and )?@dependabot-preview(?:\[bot\])?,?/g'
    replace: ''

  - search: '/(?:and )?@dependabot(?:\[bot\])?,?/g'
    replace: ''

  - search: '/(?:and )?GitHub Action(?:\[bot\])?,?/gi'
    replace: ''
