/*
The MIT License (MIT)

Copyright (c) 2020 Slawomir Jaranowski and contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

const core = require('@actions/core');
const os = require('os');
const path = require('path');
const fs = require('fs');
const DOMParser = require('xmldom').DOMParser;
const XMLSerializer = require('xmldom').XMLSerializer;
const xpath = require('xpath');


function getSettingsPath() {
    return path.join(os.homedir(), '.m2', 'settings.xml');
}

function getSettingsTemplate() {
    const templatePath = path.join(__dirname, 'templates', 'settings.xml');
    const templateStr = fs.readFileSync(templatePath).toString();
    return new DOMParser().parseFromString(templateStr, 'text/xml');
}

function writeSettings(settingsPath, templateXml) {

    // create .m2 directory if not exists
    if (!fs.existsSync(path.dirname(settingsPath))) {
        fs.mkdirSync(path.dirname(settingsPath));
    }

    const settingStr = new XMLSerializer().serializeToString(templateXml);
    fs.writeFileSync(settingsPath, settingStr);
}

function fillServers(template) {

    const servers = core.getInput('servers');

    if (!servers) {
        return;
    }

    const serversXml = template.getElementsByTagName('servers')[0];

    JSON.parse(servers).forEach((server) => {

        const serverXml = template.createElement('server');
        serversXml.appendChild(serverXml);

        for (const key in server) {
            const keyXml = template.createElement(key);
            keyXml.textContent = server[key];
            serverXml.appendChild(keyXml);
        }
    });
}

function activateProfile(template, profileId) {
    const activeByDefault = xpath
        .select(`/settings/profiles/profile[id[contains(text(),"${profileId}")]]/activation/activeByDefault`, template);

    if (activeByDefault) {
        activeByDefault[0].textContent = 'true';
    }
}

function fillProperties(template) {

    const properties = core.getInput('properties');
    if (!properties) {
        return;
    }

    activateProfile(template, '_properties_')
    const propertiesXml = xpath
        .select(`/settings/profiles/profile[id[contains(text(),"_properties_")]]/properties`, template)[0];

    JSON.parse(properties).forEach((property) => {

        for (const key in property) {
            const keyXml = template.createElement(key);
            keyXml.textContent = property[key];
            propertiesXml.appendChild(keyXml);
        }
    });
}

function addSonatypeSnapshots(template) {
    const val = core.getInput('sonatypeSnapshots');
    if (val && val.toLocaleLowerCase() == 'true') {
        activateProfile(template, '_sonatype-snapshots_')
    }
}

function generate() {

    const settingsPath = getSettingsPath();

    core.info('Prepare maven setings: ' + settingsPath);

    if (fs.existsSync(settingsPath)) {
        const val = core.getInput("override");
        if (val && val.toLocaleLowerCase() == 'true') {
            core.info('maven settings.xml already exists - override');
        } else {
            core.warning('maven settings.xml already exists - skip');
            return;
        }
    }

    const templateXml = getSettingsTemplate();
    fillServers(templateXml);
    fillProperties(templateXml);
    addSonatypeSnapshots(templateXml);
    writeSettings(settingsPath, templateXml);
    core.saveState('maven-settings', 'ok');
}

function cleanup() {

    const mavenSettingsState = core.getState('maven-settings');
    const settingsPath = getSettingsPath();
    if (mavenSettingsState == 'ok') {
        if (fs.existsSync(settingsPath)) {
            fs.unlinkSync(settingsPath);
            core.info('Cleanup maven setings: ' + settingsPath + ' - file was removed');
        } else {
            core.warning('Cleanup maven setings: ' + settingsPath + ' - file not exist');
        }
    } else {
        core.info('Cleanup maven setings: ' + settingsPath + ' - file wasn\'t generated by action');
    }
}

module.exports = {
    getSettingsTemplate,
    writeSettings,
    fillServers,
    fillProperties,
    addSonatypeSnapshots,
    generate,
    cleanup
}
